default: &default
  adapter: postgresql
  encoding: utf8
  database: test_variant
  username: postgres
  password: 
  host: localhost
  port: 5432

development:
  <<: *default
  database: test_variant_dev

test:
  <<: *default
  database: test_variant_test
